title: Dead Dock
description: A place for all my writings attempts
theme: just-the-docs

url: grammaton.github.io/thedock

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
