title: Dead Dock
description: A place for all my writings attempts
theme: just-the-docs

url: grammaton.github.io/thedock

aux_links:
  LEAP: https://l-e-a-p.github.io

heading_anchors: true

# For copy button on code
enable_copy_code_button: true

callouts:
  etimo:
    title: Etimologia
    color: purple

# Define Jekyll collections
collections:
  st:
    permalink: "/:collection/:path"
    output: true
  cad:
    permalink: "/:collection/:path"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    cad:
      name: cad
      nav_fold: true  # note: this option is new in v0.4
    st:
      name: st
      nav_fold: true  # note: this option is new in v0.4

footer_content: 'Giuseppe Silvi'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
